astra_db:
  collection_name: "ecomchatbot"

embedding_model:
  model_name: "models/text-embedding-004"
  provider: "google"

retriever:
  top_k: 3

llm:
  model_name: "gemini-2.0-flash"
  provider: "google"

